# https://github.com/marketplace/actions/mdbook-action#getting-started

name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.10.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Install Poetry for Python
        uses: snok/install-poetry@v1

      - name: Create a Python virtual env
        run: python -m venv venv

      - name: Activate the virtual env
        run: source venv/bin/activate

      - name: Explicitly tell Poetry which virtual env to use
        run: poetry env use venv/bin/python

      - name: Check which virtual env is being used
        run: poetry env info

      - name: Install Python dependencies
        run: poetry install

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "0.4.10"
          # mdbook-version: 'latest'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
